### PR TITLE
Updated cities info.

### PR DESCRIPTION
**Pull request by dimaty**
<@artem>, <@panchenko> Please review.

### CODE REVIEW

**Comment by dimaty** [comment]
<@artem>, <@panchenko> Please review.

**Comment by dimaty** [comment]
Comment.

**Comment by dimaty** [comment]
Comment

**Comment by dimaty** [comment]
Test

**Review by art-tykh — APPROVED** [review]

**Comment by dimaty** [comment]
<@artem>, <@panchenko> Please review.

**Comment by dimaty** [comment]
<@artem> Testing hook for slack.

**Pull request merged**
